spring.datasource.url=jdbc:postgresql://localhost:5433/smjestaj
spring.datasource.username=student
spring.datasource.password=student123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
